#!/bin/bash
export BSD500_DATA_DIR='$CCCSCRATCHDIR/'
export BSD68_DATA_DIR='$CCCSCRATCHDIR/'
export DIV2K_DATA_DIR='$CCCSCRATCHDIR/'
export LOGS_DIR='$CCCSCRATCHDIR/'
export CHECKPOINTS_DIR='$CCCSCRATCHDIR/'
